// lib/data.ts
const dummyData = {
  categories: [
    {
      name: "Burgers",
      name_ar: "برجر",
      description: "Juicy grilled burgers",
      description_ar: "برجر مشوي طازج وشهي",
    },
    {
      name: "Pizzas",
      name_ar: "بيتزا",
      description: "Oven-baked cheesy pizzas",
      description_ar: "بيتزا بالجبنة مخبوزة على الفرن",
    },
    {
      name: "Burritos",
      name_ar: "بوريتو",
      description: "Rolled Mexican delights",
      description_ar: "لفائف مكسيكية شهية",
    },
    {
      name: "Sandwiches",
      name_ar: "ساندويتشات",
      description: "Stacked and stuffed sandwiches",
      description_ar: "ساندويتشات محشوة بطبقات لذيذة",
    },
    {
      name: "Wraps",
      name_ar: "راب",
      description: "Rolled up wraps packed with flavor",
      description_ar: "لفائف راب مليئة بالنكهة",
    },
    {
      name: "Bowls",
      name_ar: "أطباق",
      description: "Balanced rice and protein bowls",
      description_ar: "أطباق أرز وبروتين متوازنة",
    },
  ],

  customizations: [
    // Toppings
    { name: "Extra Cheese", price: 25, type: "topping" },
    { name: "Jalapeños", price: 20, type: "topping" },
    { name: "Onions", price: 10, type: "topping" },
    { name: "Olives", price: 15, type: "topping" },
    { name: "Mushrooms", price: 18, type: "topping" },
    { name: "Tomatoes", price: 10, type: "topping" },
    { name: "Bacon", price: 30, type: "topping" },
    { name: "Avocado", price: 35, type: "topping" },

    // Sides
    { name: "Coke", price: 30, type: "side" },
    { name: "Fries", price: 35, type: "side" },
    { name: "Garlic Bread", price: 40, type: "side" },
    { name: "Chicken Nuggets", price: 50, type: "side" },
    { name: "Iced Tea", price: 28, type: "side" },
    { name: "Salad", price: 33, type: "side" },
    { name: "Potato Wedges", price: 38, type: "side" },
    { name: "Mozzarella Sticks", price: 45, type: "side" },
    { name: "Sweet Corn", price: 25, type: "side" },
    { name: "Choco Lava Cake", price: 42, type: "side" },
  ],

  menu: [
    {
      name: "Classic Cheeseburger",
      name_ar: "تشيز برجر كلاسيك",
      description: "Beef patty, cheese, lettuce, tomato",
      description_ar: "قطعة لحم بقري، جبنة، خس، طماطم",
      image_url:
        "https://static.vecteezy.com/system/resources/thumbnails/044/844/600/small/homemade-fresh-tasty-burger-with-meat-and-cheese-classic-cheese-burger-and-vegetable-ai-generated-free-png.png",
      price: 25.99,
      rating: 4.5,
      calories: 550,
      protein: 25,
      category_name: "Burgers",
      customizations: ["Extra Cheese", "Coke", "Fries", "Onions", "Bacon"],
    },
    {
      name: "Pepperoni Pizza",
      name_ar: "بيتزا ببروني",
      description: "Loaded with cheese and pepperoni slices",
      description_ar: "محملة بالجبنة وشرائح الببروني",
      image_url:
        "https://static.vecteezy.com/system/resources/thumbnails/023/742/417/small/pepperoni-pizza-isolated-illustration-ai-generative-free-png.png",
      price: 30.99,
      rating: 4.7,
      calories: 700,
      protein: 30,
      category_name: "Pizzas",
      customizations: [
        "Extra Cheese",
        "Jalapeños",
        "Garlic Bread",
        "Coke",
        "Olives",
      ],
    },
    {
      name: "Bean Burrito",
      name_ar: "بوريتو الفاصوليا",
      description: "Stuffed with beans, rice, salsa",
      description_ar: "محشو بالفاصوليا والأرز والصلصة",
      image_url:
        "https://static.vecteezy.com/system/resources/thumbnails/055/133/581/small/deliciously-grilled-burritos-filled-with-beans-corn-and-fresh-vegetables-served-with-lime-wedge-and-cilantro-isolated-on-transparent-background-free-png.png",
      price: 20.99,
      rating: 4.2,
      calories: 480,
      protein: 18,
      category_name: "Burritos",
      customizations: ["Jalapeños", "Iced Tea", "Fries", "Salad"],
    },
    {
      name: "BBQ Bacon Burger",
      name_ar: "برجر البيكون بالباربكيو",
      description: "Smoky BBQ sauce, crispy bacon, cheddar",
      description_ar: "صلصة باربكيو مدخنة، بيكون مقرمش، جبنة تشيدر",
      image_url:
        "https://static.vecteezy.com/system/resources/thumbnails/060/236/245/small/a-large-hamburger-with-cheese-onions-and-lettuce-free-png.png",
      price: 27.5,
      rating: 4.8,
      calories: 650,
      protein: 29,
      category_name: "Burgers",
      customizations: ["Onions", "Fries", "Coke", "Bacon", "Avocado"],
    },
    {
      name: "Chicken Caesar Wrap",
      name_ar: "راب سيزر بالدجاج",
      description: "Grilled chicken, lettuce, Caesar dressing",
      description_ar: "دجاج مشوي، خس، صوص سيزر",
      image_url:
        "https://static.vecteezy.com/system/resources/thumbnails/048/930/603/small/caesar-wrap-grilled-chicken-isolated-on-transparent-background-free-png.png",
      price: 21.5,
      rating: 4.4,
      calories: 490,
      protein: 28,
      category_name: "Wraps",
      customizations: ["Extra Cheese", "Coke", "Potato Wedges", "Tomatoes"],
    },
    {
      name: "Grilled Veggie Sandwich",
      name_ar: "ساندويتش الخضار المشوي",
      description: "Roasted veggies, pesto, cheese",
      description_ar: "خضار محمصة، صوص بيستو، جبنة",
      image_url:
        "https://static.vecteezy.com/system/resources/thumbnails/047/832/012/small/grilled-sesame-seed-bread-veggie-sandwich-with-tomato-and-onion-free-png.png",
      price: 19.99,
      rating: 4.1,
      calories: 420,
      protein: 19,
      category_name: "Sandwiches",
      customizations: ["Mushrooms", "Olives", "Mozzarella Sticks", "Iced Tea"],
    },
    {
      name: "Double Patty Burger",
      name_ar: "دبل تشيز برجر",
      description: "Two juicy beef patties and cheese",
      description_ar: "قطعتان من اللحم البقري الطازج مع الجبنة",
      image_url:
        "https://static.vecteezy.com/system/resources/thumbnails/060/359/627/small/double-cheeseburger-with-lettuce-tomatoes-cheese-and-sesame-bun-free-png.png",
      price: 32.99,
      rating: 4.9,
      calories: 720,
      protein: 35,
      category_name: "Burgers",
      customizations: [
        "Extra Cheese",
        "Onions",
        "Fries",
        "Coke",
        "Chicken Nuggets",
      ],
    },
    {
      name: "Paneer Tikka Wrap",
      name_ar: "راب بانير تكة",
      description: "Spicy paneer, mint chutney, veggies",
      description_ar: "بانير حار، صوص النعناع، خضار",
      image_url:
        "https://static.vecteezy.com/system/resources/thumbnails/057/913/530/small/delicious-wraps-a-tantalizing-array-of-wraps-filled-with-vibrant-vegetables-succulent-fillings-and-fresh-ingredients-artfully-arranged-for-a-mouthwatering-culinary-experience-free-png.png",
      price: 23.99,
      rating: 4.6,
      calories: 470,
      protein: 20,
      category_name: "Wraps",
      customizations: ["Jalapeños", "Tomatoes", "Salad", "Fries", "Iced Tea"],
    },
    {
      name: "Mexican Burrito Bowl",
      name_ar: "طبق بوريتو مكسيكي",
      description: "Rice, beans, corn, guac, salsa",
      description_ar: "أرز، فاصوليا، ذرة، جواكامولي، صلصة",
      image_url:
        "https://static.vecteezy.com/system/resources/thumbnails/057/466/374/small/healthy-quinoa-bowl-with-avocado-tomato-and-black-beans-ingredients-free-png.png",
      price: 26.49,
      rating: 4.7,
      calories: 610,
      protein: 24,
      category_name: "Bowls",
      customizations: ["Avocado", "Sweet Corn", "Salad", "Iced Tea"],
    },
    {
      name: "Spicy Chicken Sandwich",
      name_ar: "ساندويتش الدجاج الحار",
      description: "Crispy chicken, spicy sauce, pickles",
      description_ar: "دجاج مقرمش، صوص حار، مخلل",
      image_url:
        "https://static.vecteezy.com/system/resources/thumbnails/051/814/008/small/a-grilled-chicken-sandwich-with-lettuce-and-tomatoes-free-png.png",
      price: 24.99,
      rating: 4.3,
      calories: 540,
      protein: 26,
      category_name: "Sandwiches",
      customizations: [
        "Jalapeños",
        "Onions",
        "Fries",
        "Coke",
        "Choco Lava Cake",
      ],
    },
    {
      name: "Classic Margherita Pizza",
      name_ar: "بيتزا مارجريتا كلاسيك",
      description: "Tomato, mozzarella, fresh basil",
      description_ar: "طماطم، موزاريلا، ريحان طازج",
      image_url:
        "https://static.vecteezy.com/system/resources/thumbnails/058/700/845/small/free-isolated-on-transparent-background-delicious-pizza-topped-with-fresh-tomatoes-basil-and-melted-cheese-perfect-for-food-free-png.png",
      price: 26.99,
      rating: 4.1,
      calories: 590,
      protein: 21,
      category_name: "Pizzas",
      customizations: ["Extra Cheese", "Olives", "Coke", "Garlic Bread"],
    },
    {
      name: "Protein Power Bowl",
      name_ar: "طبق البروتين",
      description: "Grilled chicken, quinoa, veggies",
      description_ar: "دجاج مشوي، كينوا، خضار",
      image_url:
        "https://static.vecteezy.com/system/resources/thumbnails/056/106/379/small/top-view-salad-with-chicken-avocado-tomatoes-and-lettuce-free-png.png",
      price: 29.99,
      rating: 4.8,
      calories: 580,
      protein: 38,
      category_name: "Bowls",
      customizations: ["Avocado", "Salad", "Sweet Corn", "Iced Tea"],
    },
    {
      name: "Paneer Burrito",
      name_ar: "بوريتو البانير",
      description: "Paneer cubes, spicy masala, rice, beans",
      description_ar: "مكعبات بانير، ماسالا حارة، أرز، فاصوليا",
      image_url:
        "https://static.vecteezy.com/system/resources/thumbnails/056/565/254/small/burrito-with-cauliflower-and-vegetables-free-png.png",
      price: 24.99,
      rating: 4.2,
      calories: 510,
      protein: 22,
      category_name: "Burritos",
      customizations: ["Jalapeños", "Fries", "Garlic Bread", "Coke"],
    },
    {
      name: "Chicken Club Sandwich",
      name_ar: "ساندويتش كلوب بالدجاج",
      description: "Grilled chicken, lettuce, cheese, tomato",
      description_ar: "دجاج مشوي، خس، جبنة، طماطم",
      image_url:
        "https://static.vecteezy.com/system/resources/thumbnails/060/364/135/small/a-flavorful-club-sandwich-with-turkey-bacon-and-fresh-vegetables-sliced-and-isolated-on-a-transparent-background-free-png.png",
      price: 27.49,
      rating: 4.5,
      calories: 610,
      protein: 31,
      category_name: "Sandwiches",
      customizations: ["Bacon", "Tomatoes", "Mozzarella Sticks", "Iced Tea"],
    },
  ],
};

export default dummyData;
